-- Run this in the Supabase SQL Editor

-- 1. Create the Practice Sessions Table
create table practice_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  sentence_text text not null,
  accuracy numeric not null,
  per numeric not null,
  phonemes jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable Row Level Security (Security Policies)
alter table practice_sessions enable row level security;

-- 3. Policy: Allow users to view their own data
create policy "Users can read own sessions"
  on practice_sessions for select
  using ( auth.uid() = user_id );

-- 4. Policy: Allow users to insert their own data
create policy "Users can insert own sessions"
  on practice_sessions for insert
  with check ( auth.uid() = user_id );

-- 5. Optional: Policy to allow users to delete their own data
create policy "Users can delete own sessions"
  on practice_sessions for delete
  using ( auth.uid() = user_id );
